# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Project\TestSeq\UI\automation.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_automation(object):
    def setupUi(self, automation):
        automation.setObjectName("automation")
        automation.resize(1024, 591)
        self.gridLayout = QtWidgets.QGridLayout(automation)
        self.gridLayout.setObjectName("gridLayout")
        self.lb_title = QtWidgets.QLabel(automation)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lb_title.setFont(font)
        self.lb_title.setObjectName("lb_title")
        self.gridLayout.addWidget(self.lb_title, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lb_io = QtWidgets.QLabel(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_io.sizePolicy().hasHeightForWidth())
        self.lb_io.setSizePolicy(sizePolicy)
        self.lb_io.setMaximumSize(QtCore.QSize(16777215, 10000))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_io.setFont(font)
        self.lb_io.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lb_io.setObjectName("lb_io")
        self.gridLayout_2.addWidget(self.lb_io, 0, 0, 1, 1)
        self.tw_io = QtWidgets.QTableWidget(automation)
        self.tw_io.setObjectName("tw_io")
        self.tw_io.setColumnCount(0)
        self.tw_io.setRowCount(0)
        self.gridLayout_2.addWidget(self.tw_io, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 3, 8, 1)
        self.lb_axis = QtWidgets.QLabel(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_axis.sizePolicy().hasHeightForWidth())
        self.lb_axis.setSizePolicy(sizePolicy)
        self.lb_axis.setMaximumSize(QtCore.QSize(16777215, 10000))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_axis.setFont(font)
        self.lb_axis.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lb_axis.setObjectName("lb_axis")
        self.gridLayout.addWidget(self.lb_axis, 1, 0, 1, 1)
        self.cb_axis = QtWidgets.QComboBox(automation)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cb_axis.setFont(font)
        self.cb_axis.setMaxVisibleItems(10)
        self.cb_axis.setObjectName("cb_axis")
        self.gridLayout.addWidget(self.cb_axis, 2, 0, 1, 1)
        self.lb_real_pos = QtWidgets.QLabel(automation)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_real_pos.setFont(font)
        self.lb_real_pos.setObjectName("lb_real_pos")
        self.gridLayout.addWidget(self.lb_real_pos, 3, 0, 1, 1)
        self.dsb_real_pos = QtWidgets.QDoubleSpinBox(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_real_pos.sizePolicy().hasHeightForWidth())
        self.dsb_real_pos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_real_pos.setFont(font)
        self.dsb_real_pos.setMaximum(10000.0)
        self.dsb_real_pos.setObjectName("dsb_real_pos")
        self.gridLayout.addWidget(self.dsb_real_pos, 3, 1, 1, 1)
        self.pb_jog1 = QtWidgets.QPushButton(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_jog1.sizePolicy().hasHeightForWidth())
        self.pb_jog1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_jog1.setFont(font)
        self.pb_jog1.setObjectName("pb_jog1")
        self.gridLayout.addWidget(self.pb_jog1, 3, 2, 1, 1)
        self.lb_man_speed = QtWidgets.QLabel(automation)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_man_speed.setFont(font)
        self.lb_man_speed.setObjectName("lb_man_speed")
        self.gridLayout.addWidget(self.lb_man_speed, 4, 0, 1, 1)
        self.dsb_speed = QtWidgets.QDoubleSpinBox(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_speed.sizePolicy().hasHeightForWidth())
        self.dsb_speed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_speed.setFont(font)
        self.dsb_speed.setMaximum(10000.0)
        self.dsb_speed.setObjectName("dsb_speed")
        self.gridLayout.addWidget(self.dsb_speed, 4, 1, 1, 1)
        self.pb_jog2 = QtWidgets.QPushButton(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_jog2.sizePolicy().hasHeightForWidth())
        self.pb_jog2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_jog2.setFont(font)
        self.pb_jog2.setObjectName("pb_jog2")
        self.gridLayout.addWidget(self.pb_jog2, 4, 2, 1, 1)
        self.lb_step = QtWidgets.QLabel(automation)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_step.setFont(font)
        self.lb_step.setObjectName("lb_step")
        self.gridLayout.addWidget(self.lb_step, 5, 0, 1, 1)
        self.dsb_step = QtWidgets.QDoubleSpinBox(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsb_step.sizePolicy().hasHeightForWidth())
        self.dsb_step.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dsb_step.setFont(font)
        self.dsb_step.setMaximum(10000.0)
        self.dsb_step.setObjectName("dsb_step")
        self.gridLayout.addWidget(self.dsb_step, 5, 1, 1, 1)
        self.pb_absolute = QtWidgets.QPushButton(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_absolute.sizePolicy().hasHeightForWidth())
        self.pb_absolute.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_absolute.setFont(font)
        self.pb_absolute.setObjectName("pb_absolute")
        self.gridLayout.addWidget(self.pb_absolute, 5, 2, 1, 1)
        self.pb_reset = QtWidgets.QPushButton(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_reset.sizePolicy().hasHeightForWidth())
        self.pb_reset.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_reset.setFont(font)
        self.pb_reset.setObjectName("pb_reset")
        self.gridLayout.addWidget(self.pb_reset, 6, 0, 1, 1)
        self.pb_axis_stop = QtWidgets.QPushButton(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_axis_stop.sizePolicy().hasHeightForWidth())
        self.pb_axis_stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_axis_stop.setFont(font)
        self.pb_axis_stop.setObjectName("pb_axis_stop")
        self.gridLayout.addWidget(self.pb_axis_stop, 6, 1, 1, 1)
        self.pb_relative = QtWidgets.QPushButton(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_relative.sizePolicy().hasHeightForWidth())
        self.pb_relative.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_relative.setFont(font)
        self.pb_relative.setObjectName("pb_relative")
        self.gridLayout.addWidget(self.pb_relative, 6, 2, 1, 1)
        self.cb_zero = QtWidgets.QCheckBox(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_zero.sizePolicy().hasHeightForWidth())
        self.cb_zero.setSizePolicy(sizePolicy)
        self.cb_zero.setObjectName("cb_zero")
        self.gridLayout.addWidget(self.cb_zero, 7, 0, 1, 1)
        self.cb_limitm = QtWidgets.QCheckBox(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_limitm.sizePolicy().hasHeightForWidth())
        self.cb_limitm.setSizePolicy(sizePolicy)
        self.cb_limitm.setObjectName("cb_limitm")
        self.gridLayout.addWidget(self.cb_limitm, 7, 1, 1, 1)
        self.cb_limitp = QtWidgets.QCheckBox(automation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_limitp.sizePolicy().hasHeightForWidth())
        self.cb_limitp.setSizePolicy(sizePolicy)
        self.cb_limitp.setObjectName("cb_limitp")
        self.gridLayout.addWidget(self.cb_limitp, 7, 2, 1, 1)

        self.retranslateUi(automation)
        QtCore.QMetaObject.connectSlotsByName(automation)

    def retranslateUi(self, automation):
        _translate = QtCore.QCoreApplication.translate
        automation.setWindowTitle(_translate("automation", "Automation"))
        self.lb_title.setText(_translate("automation", "AutoMation"))
        self.lb_io.setText(_translate("automation", "IO Setting:"))
        self.lb_axis.setText(_translate("automation", "Axis Name："))
        self.lb_real_pos.setText(_translate("automation", "Current Position:"))
        self.pb_jog1.setText(_translate("automation", "Jog+"))
        self.lb_man_speed.setText(_translate("automation", "Manual Speed:"))
        self.pb_jog2.setText(_translate("automation", "Jog-"))
        self.lb_step.setText(_translate("automation", "Distance:"))
        self.pb_absolute.setText(_translate("automation", "Absolute"))
        self.pb_reset.setText(_translate("automation", "Reset"))
        self.pb_axis_stop.setText(_translate("automation", "Stop"))
        self.pb_relative.setText(_translate("automation", "Relative"))
        self.cb_zero.setText(_translate("automation", "Zero"))
        self.cb_limitm.setText(_translate("automation", "Limit-"))
        self.cb_limitp.setText(_translate("automation", "Limit+"))

